apiVersion: batch/v1
kind: Job
metadata:
  name: after
  annotations:
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/hook.post-sync: |
      #!/bin/bash
      set -euo pipefail
      kubectl get service/kustomize-guestbook-ui -o jsonpath='{.spec.clusterIP}' -n argocd
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: ["sleep", "10"]
      restartPolicy: Never
  backoffLimit: 0
